synopsis:
  - type: SRSWR
    width: 1000, 2000, 5000

  - type: SRSWR
    width: 10000, 20000, 50000

aggregation:
  - type: MIN
    inputFile: "data/some_input_file.csv"
    fieldNameAgg: "value"
    accuracyFile: "data/some_min_acc_file.csv"
    fieldNameApprox: "aggregation"

  - type: MAX
    inputFile: "data/some_input_file.csv"
    fieldNameAgg: "value"
    accuracyFile: "data/some_max_acc_file.csv"
    fieldNameApprox: "aggregation"

  - type: SUM
    inputFile: "data/some_other_input_file.csv"
    fieldNameAgg: "value1"
    accuracyFile: "data/some_sum_acc_file.csv"
    fieldNameApprox: "aggregation"

  - type: AVERAGE
    inputFile: "data/some_other_input_file.csv"
    fieldNameAgg: "value2"
    accuracyFile: "data/some_average_acc_file.csv"
    fieldNameApprox: "aggregation"

  - type: COUNT
    inputFile: "data/some_other_input_file.csv"
    fieldNameAgg: "value2"
    accuracyFile: "data/some_count_acc_file.csv"
    fieldNameApprox: "aggregation"

windowSize: 1000, 5000, 10000, 50000, 100000
csvFilename: "output_csvfile.csv"
reps: 10