synopsis:
  - type: SRSWR
    width: 1000, 2000, 5000

  - type: SRSWR
    width: 10000, 20000, 50000

aggregation:
  - type: min
    accuracyFile: "data/some_min_acc_file.csv"
    inputFile: "data/some_input_file.csv"
    schema: "schema1"
    fieldNameAgg: "value"
    finalType: INT64

  - type: max
    accuracyFile: "data/some_max_acc_file.csv"
    inputFile: "data/some_input_file.csv"
    schema: "schema1"
    fieldNameAgg: "value"
    finalType: INT64

  - type: sum
    accuracyFile: "data/some_sum_acc_file.csv"
    inputFile: "data/some_other_input_file.csv"
    schema: "schema2"
    fieldNameAgg: "value"
    finalType: INT64

  - type: average
    accuracyFile: "data/some_average_acc_file.csv"
    inputFile: "data/some_input_file.csv"
    schema: "schema1"
    fieldNameAgg: "value"
    finalType: INT64

windowSize: 1000, 5000, 10000, 50000, 100000
csvFilename: "output_csvfile.csv"
reps: 10