cache: ccache
language: ruby

services:
        - docker

before_install:
        - docker pull nebulastream/nes-build-image:latest 
script:
        - docker run -v /home/travis/build/nebulastream/IoTDB/iotdb:/iotdb nebulastream/nes-build-image

notifications:
  email: false
