os: linux
dist: xenial

language: cpp
compiler: clang

before_install:
  - sudo apt-get update
  - sudo apt-get install -y clang-3.8
  - sudo apt-get install -y libzmq-dev
  - sudo apt-get install -y libboost1.58-all-dev
  - sudo apt-get install -y zlib1g-dev
  - sudo apt-get install -y libclang-dev
  - sudo apt-get install -y llvm

script:
  - cd iotdb
  - mkdir debug-build && cd debug-build
  - export CC=/usr/lib/llvm-3.8/bin/clang
  - export CXX=/usr/lib/llvm-3.8/bin/clang++
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
