matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-3.8
          packages:
            - clang-3.8
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get update
  - sudo apt-get install -y libzmq-dev
  - sudo apt-get install -y libboost1.58-all-dev
  - sudo apt-get install -y zlib1g-dev
  - sudo apt-get install -y libclang-dev

script:
  - cd iotdb
  - llvm-config --includedir
  - mkdir debug-build && cd debug-build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make

notifications:
  email: false
