matrix:
  include:
    os: linux
    dist: bionic
    addons:
      apt:
        packages:
          clang-3.9
          llvm-3.9-dev

language: cpp
compiler: gcc

before_install:
  - sudo apt-get update
  - sudo apt remove -y llvm-6.0
  - sudo apt autoremove
  - sudo apt-get install -y clang-3.9
  - sudo apt-get install -y llvm-3.9-dev
  - sudo apt-get install -y libclang-dev
  - sudo apt-get install -y libzmq3-dev
  - sudo apt-get install -y libboost1.65-all-dev
  - sudo apt-get install -y liblog4cxx-dev
  - sudo apt-get install -y libcpprest-dev
  - sudo apt-get install -y libssl-dev
script:
  - clang --version
  - clang++ --version
  - sudo apt list --installed | grep llvm
  - cd iotdb && mkdir debug-build && cd debug-build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBoost_NO_SYSTEM_PATHS=TRUE -DBoost_INCLUDE_DIR="/usr/include" -DBoost_LIBRARY_DIR="/usr/lib/x86_64-linux-gnu" ..
  - make -j8 && make test_debug

notifications:
  email: false
