os: linux
dist: xenial
     

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libzmq-dev
  - sudo apt-get install -y libboost1.58-all-dev
 
script:
  - cd iotdb
  - llvm-config --includedir
  - mkdir debug-build && cd debug-build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make

notifications:
  email: false
