matrix:
  include:
    os: linux
    dist: xenial
    addons:
      apt:
        packages:
          clang-3.8
          llvm-3.8-dev
    env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"

language: cpp
compiler: clang

before_install:
  - eval "${EVAL}"
  - ls /usr/include -la
  - ls /usr/lib/llvm-3.8/include -la
  - ls /usr/lib/llvm-3.8/includ/polly -la
  - sudo apt-get update
  - sudo apt-get install -y libclang-dev
  - sudo apt-get install -y libzmq-dev
  - sudo apt-get install -y libboost1.58-all-dev
 
script:
  - cd iotdb
  - llvm-config --includedir
  - mkdir debug-build && cd debug-build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DTRAVIS_INCLUDE_DIR=/usr/lib/llvm-3.8/include ..
  - make

notifications:
  email: false
