# ~~~ Configurations for the NES E2E Selection Benchmark ~~~

#Location of query set
# For each query set we will run the experiments
querySetLocation: '/home/ankit-ldap/tmp/nes/benchmark/src/Micro-Benchmarks/Query-Merger/QueryLoad'

# Parameter that are changed per run with comma separated list
queryMergerRule: DefaultQueryMergerRule,StringSignatureBasedCompleteQueryMergerRule,ImprovedStringSignatureBasedCompleteQueryMergerRule,Z3SignatureBasedCompleteQueryMergerRule
noOfPhysicalSources: 1,1,1,1

#benchmark internal parameter
logLevel: LOG_TRACE
startupSleepIntervalInSeconds: 3
numberOfMeasurementsToCollect: 3
