# ~~~ Configurations for the NES E2E Selection Benchmark ~~~

#Location of query set
# For each query set we will run the experiments
querySetLocation: '/home/ankit-ldap/tmp/nes/benchmark/src/Micro-Benchmarks/Query-Merger/QueryLoad'
#querySetLocation: '/home/ankit/dima/nes/benchmark/src/Micro-Benchmarks/Query-Merger/QueryLoad'

# Parameter that are changed per run with comma separated list
queryMergerRule: Z3SignatureBasedCompleteQueryMergerRule,SyntaxBasedCompleteQueryMergerRule,HybridCompleteQueryMergerRule,DefaultQueryMergerRule,StringSignatureBasedCompleteQueryMergerRule,ImprovedStringSignatureBasedCompleteQueryMergerRule
#queryMergerRule: Z3SignatureBasedPartialQueryMergerRule,SyntaxBasedPartialQueryMergerRule,DefaultQueryMergerRule,StringSignatureBasedPartialQueryMergerRule,ImprovedStringSignatureBasedPartialQueryMergerRule
noOfPhysicalSources: 1,1,1,1,1
batchSize: 1,1,1,1,1

#benchmark internal parameter
logLevel: LOG_NONE
numberOfDistinctSources: 10
startupSleepIntervalInSeconds: 3
numberOfMeasurementsToCollect: 1
