# ~~~ Configurations for the NES Coordinator ~~~

# ~~ IPs and Ports ~~
# Set NES ip of the REST server
restIp:

# Set RPC IP address of NES Coordinator
coordinatorIp:

# Set RPC Server port of NES Coordinator
rpcPort:

# Set port exposed for REST endpoints
restPort:

# Set the data port of the network manager
dataPort:


# ~~ Processing Configurations ~~
# Set the number of computing slots in NES Coordinator
numberOfSlots:

# The log level (LOG_NONE, LOG_WARNING, LOG_DEBUG, LOG_INFO, LOG_TRACE)
logLevel:

# Number buffers in global buffer pool
numberOfBuffersInGlobalBufferManager:

# Number buffers in task local buffer pool
numberOfBuffersPerWorker:

# Number buffers in source local buffer pool
numberOfBuffersInSourceLocalBufferPool:

# Size of buffer to pass data through the system
bufferSizeInBytes:

# Number of threads available for the worker node. Defines how many queries can run in parallel.
numWorkerThreads:

# The number of queries to be processed together
queryBatchSize:

# The rule to be used for performing query merging
queryMergerRule:

# Semantic Query Validation Feature
enableSemanticQueryValidation:

# Enable monitoring
enableMonitoring:

# Selects the memory layout selection policy can be [FORCE_ROW_LAYOUT|FORCE_COLUMN_LAYOUT]
memoryLayoutPolicy:

# Perform only source operator duplication when applying Logical Source Expansion Rewrite Rule
performOnlySourceOperatorExpansion:

# Enable reconfiguration of running query plans
enableQueryReconfiguration: