# ~~~ Configurations for the NES Worker ~~~

# ~~ IPs and Ports ~~
# IP address of the worker node. Default: 127.0.0.1
localWorkerIp:

# Set IP address of Coordinator to which the Worker should connect. Default: 127.0.0.1
coordinatorIp:

# Set RPC Server port of NES Coordinator to which the NES Worker should connect
# Needs to be the same as rpcPort in Coordinator. Default: 4000
coordinatorPort:

# Set RPC server port of NES Worker. Default: 5000
rpcPort:

# Set the data port of the NES Worker. Default: 5001
dataPort:

# Set number of computing slots in NES Worker. Default: UINT16_MAX
numberOfSlots:

# Set the number of worker threads. Default: 1
numWorkerThreads:

# Number buffers in global buffer pool. Default: 1024
numberOfBuffersInGlobalBufferManager:

# Number buffers in task local buffer pool. Default: 128
numberOfBuffersPerWorker:

# Number buffers in source local buffer pool. Default: 64
numberOfBuffersInSourceLocalBufferPool:

# Size of buffer to pass data through the system. Default: 4096
bufferSizeInBytes:

# Set parentId of NES Worker node. Default: 0
parentId:

# The log level (LOG_NONE, LOG_WARNING, LOG_DEBUG, LOG_INFO, LOG_TRACE). Default: LOG_DEBUG
logLevel:

# Indicates the optimization strategy for the query compiler [FAST|DEBUG|OPTIMIZE]. Default: OPTIMIZE
queryCompilerCompilationStrategy:

# Indicates the pipelining strategy for the query compiler [OPERATOR_FUSION|OPERATOR_AT_A_TIME]. Default: OPERATOR_FUSION
queryCompilerPipeliningStrategy:

# Indicates the OutputBufferAllocationStrategy [ALL|NO|ONLY_INPLACE_OPERATIONS_NO_FALLBACK,
# |REUSE_INPUT_BUFFER_AND_OMIT_OVERFLOW_CHECK_NO_FALLBACK,|REUSE_INPUT_BUFFER_NO_FALLBACK|OMIT_OVERFLOW_CHECK_NO_FALLBACK]
# Default: ALL
queryCompilerOutputBufferOptimizationLevel:

# Comma separated list of where to map the sources. Default: ""
sourcePinList:

# Comma separated list of where to map the worker. Default: ""
workerPinList:

# Enable Numa-Aware execution. Default: false
numaAwareness:

# Enable monitoring. Default: false
enableMonitoring:

# ~~~ Physical Stream Configurations ~~~

# A Physical Stream may be associated with multiple Instances of a logicalStreamName, a physicalStreamName and a SourceType
# If no Physical Stream Config is given, the worker will be created without a physical stream
# Available source Types: DefaultSource, CSVSource, MQTTSource, SenseSource, OPCSource (ToDo: Make source available),
#                         ZMQSource (ToDo: Make source available), KafkaSource (ToDo: Make source available),
#                         BinarySource (ToDo: Make source available))
# Default: empty
physicalSources:
  # Set logical stream name where this stream is added to
  - logicalSourceName:
    # Set physical stream name
    physicalSourceName:
    # Define source type, also need to specify source configurations for source type below
    type: CSV
    # CSVSource and its needed configuration params
    configuration:
      ###### Define only the following configurations for CSV stream
      # Set file path
      filePath:
      # Skip first line of the file
      skipHeader:
      # Set delimiter, e.g. ',' or '.'
      delimiter:
      # Set number of buffers to produce, i.e. how often the read csv file is repeated
      numberOfBuffersToProduce:
      # Set number of tuples to produce per buffer
      numberOfTuplesToProducePerBuffer:
      # Set sampling frequency of source
      sourceFrequency:
      ###### Define only the following configurations for DefaultSource stream
      # Set number of buffers to produce, i.e. how often the default data is repeated for this source
      #numberOfBuffersToProduce:
      ###### Define only the following configurations for BinarySource stream
      # Set number of buffers to produce, i.e. how often the default data is repeated for this source
      #filePath:
      ###### Define only the following configurations for SenseSource stream
      # Set number of buffers to produce, i.e. how often the default data is repeated for this source
      #udfs:
      ###### Define only the following configurations for MQTTSource stream
      # Set url to connect to
      #url:
      # Set clientId
      #clientId:
      # Set userName
      #userName:
      # Set topic to listen to
      #topic:
      # set quality of service
      #qos:
      # set cleanSession true = clean up session after client loses connection, false = keep data for client after connection loss (persistent session)
      #cleanSession:
      # set tupleBuffer flush interval in milliseconds
      #flushIntervalMS:
      # Set input data format
      #inputFormat:
      ###### Define only the following configurations for KafkaSource stream
      # Set kafka broker string
      #brokers:
      # Set auto commit, boolean value where 1 equals true, and 0 equals false
      #autoCommit:
      # Set groupId
      #groupId:
      # Set topic to listen to
      #topic:
      # Set connection time out for source
      #connectionTimeout:
      ###### Define only the following configurations for OPCSource stream
      # Set namespaceIndex for node, needed for: OPCSource
      #namespaceIndex:
      # Set node identifier, needed for: OPCSource
      #nodeIdentifier:
      # Set userName, needed for: OPCSource (can be chosen arbitrary), OPCSource
      #userName:
      # Set password, needed for: OPCSource
      #password: