version: "3"
services:
  coordinator:
    image: nebulastream/nes-executable-image:0.5.44
    entrypoint: ["bash", "-c", "nesCoordinator --configPath=/tutorial/coordinator.yml"]
    ports:
      - 8081:8081
    volumes:
      - ./:/tutorial
    networks:
      nebulastream-network:
        ipv4_address: 172.323.0.20
  worker:
    image: nebulastream/nes-executable-image:0.5.44
    entrypoint: ["bash", "-c", "sleep 3 && nesWorker --configPath=/tutorial/worker-1.yml"]
    volumes:
      - ./:/tutorial
    networks:
      nebulastream-network:
        ipv4_address: 172.323.0.30
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
    networks:
      nebulastream-network:
        ipv4_address: 172.33.0.110
  ui:
    image: nebulastream/nes-ui-image:latest
    ports:
      - 3000:3000
    networks:
      nebulastream-network:
        ipv4_address: 172.33.0.120
networks:
  nebulastream-network:
    ipam:
      config:
        - subnet: 172.32.0.0/24
