# ~~~ Configurations for the NES Worker ~~~

# ~~ IPs and Ports ~~
# Set IP address of NES Coordinator to which the NES Worker should connect
coordinatorIp: 0.0.0.0

# Set RPC Server port of NES Coordinator to which the NES Worker should connect
coordinatorPort: 12267

# Set RPC server port of NES Worker
rpcPort: 8081

# Set the data port of the NES Worker
dataPort: 3001

# Set worker IP
localWorkerIp: 127.0.0.1


# ~~ Source Handling ~~
# Set the source type (available options: DefaultSource, CSVSource, OPCSource, ZMQSource, KafkaSource, BinarySource, SenseSource)
sourceType:

# Set source configuration. Options depend on source type.
# DefaultSource: "" (not needed)
# CSVSource: String with path to CSV file.
# OPCSource (ToDo: Make source available): String set up as follows: "url;namespaceIndex;identifier;user;pwd"
#            where the url is a string containing the full OPC server url,
#            namespaceIndex is a uint16_t providing the namespanaceIndex for the nodeId,
#            identifier is a string containing the nodeId identifier,
#            user is a string containing the user name for server authentication ToDo: Implement server authentication.
#            pwd is a string containing the password for server authentication
# ZMQSource (ToDo: Make source available): String set up as: "host;port"
#            where host is a string containing the zmq host's ip address
#            and port is a uint16_t containing the zmq port
# KafkaSource (ToDo: Make source available): String set up as follows: "brokers;topic;groupId;autoCommit;kafkaConnectTimeout"
#            where brokers is a string containing the brokers's ip address,
#            topic is a string containing the topic,
#            groupId is a string containing the groupId,
#            autoCommit is a boolean value where 1 equals true, and 0 equals false,
#            kafkaConnectTimeout is a uint16_t providing the time out for the connection
# BinarySource: String with path to binary file.
# SenseSource (ToDo: Make source available): String with udsf inside
# YSBSource: "" (not needed)
sourceConfig:

# Set sampling frequency of source
sourceFrequency: 1

# Looping endlessly over the file
endlessRepeat: off

# Skip first line of the file
skipHeader: false

# Set number of buffers to produce
numberOfBuffersToProduce: 1

# Set number of tuples to produce per buffer
numberOfTuplesToProducePerBuffer: 0


# ~~ Processing Configurations ~~
# Set physical stream name
physicalStreamName: test_stream

# Set logical stream name where this stream is added to
logicalStreamName: default_stream

# Set parentId of NES Worker node
parentId: -1

# Set number of computing slots in NES Worker
# 0 is a place holder, default is number of processors installed in host machine
numberOfSlots: 0

# The log level (LOG_NONE, LOG_WARNING, LOG_DEBUG, LOG_INFO, LOG_TRACE)
logLevel: LOG_DEBUG