name: NES CI

on: [push, pull_request]
runs-on: self-hosted
jobs:
  build:
    runs-on: ubuntu-18.04    
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
          docker run -v $GITHUB_WORKSPACE/iotdb:/iotdb --entrypoint /iotdb/docker/scripts/entrypoint-nes-build.sh nebulastream/nes-build-image

